// Explicit: inside a build script `java` names the Java plugin extension, not the package.
import java.io.File

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
}

// Every other module, taken from the build rather than listed by hand. A module added later
// has to land on this classpath without its author knowing this file exists — otherwise flag
// discovery quietly goes back to reporting a subset, which is the bug this module fixes.
val siblingModules = rootProject.subprojects.map { it.path } - project.path

kotlin {
    jvmToolchain(21)

    jvm()

    sourceSets {
        commonMain.dependencies {
            siblingModules.forEach { implementation(project(it)) }
        }
        jvmTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            // SwayHarness, from `:wm`'s test classes. The invoke path's integration suite drives
            // a real headless sway, and reproducing "start one, and take down everything it
            // spawned" here would be a second copy of the hardest code in this repo's tests —
            // one whose drift shows up as leaked compositors on a shared machine rather than as
            // a failing test.
            implementation(project(path = ":wm", configuration = "jvmTestClasses"))
        }
    }
}

// ---------------------------------------------------------------- the launchers
//
// Every `main` in the tree, and the class the compiler puts it in. Until this existed the
// three CLIs printed `usage: awakener-config …` for a command nothing produced (#47): the
// flags doctrine's entire delivery mechanism was a `java -cp` line you had to assemble by
// hand, and a hotkey cannot be bound to one of those.
//
// All three are launched off `:cli`'s runtime classpath, including `:registry`'s, and that is
// deliberate rather than incidental. Flag discovery scans the classpath, so a `main` launched
// from a module that cannot see its siblings reports their flags as unknown keys. This module
// is the one that depends on everything, so it is the only correct place to launch any of them
// from.
val entryPoints = mapOf(
    "awakener-config" to "com.monkopedia.awakener.cli.AwakenerConfigCliKt",
    "awakener-invoke" to "com.monkopedia.awakener.cli.AwakenerInvokeCliKt",
    "awakener-registry" to "com.monkopedia.awakener.registry.RegistryCliKt",
)

// The JDK this was built with, as a last-resort fallback below. A hotkey is `exec`ed by the
// compositor with whatever environment the session has, which usually means no JAVA_HOME at
// all — and on a machine whose default `java` is older than 21 (kaladin's is 8) that turns
// one line of sway config into an UnsupportedClassVersionError naming no fix.
val buildJava: String =
    javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(21) }
        .get().executablePath.asFile.absolutePath

/** The POSIX launcher for one entry point. Deliberately small; see the comments in it. */
fun launcher(name: String, mainClass: String): String =
    """
    #!/bin/sh
    # $name — generated by `gradlew :cli:installDist`.
    # Edit cli/build.gradle.kts, not this file: it is overwritten on every build.
    set -eu

    # Resolve ${'$'}0 through any symlinks before deriving APP_HOME. A hotkey is far more likely
    # to name ~/.local/bin/$name than a path inside the install tree, and `dirname` of the
    # *link* finds no lib/ next to it — which fails as a ClassNotFoundException naming no fix.
    # Same loop Gradle's own start scripts use, and daisy-chained links work.
    app_path=${'$'}0
    while
        app_dir=${'$'}{app_path%"${'$'}{app_path##*/}"}
        [ -h "${'$'}app_path" ]
    do
        link=${'$'}(ls -ld -- "${'$'}app_path")
        link=${'$'}{link#*' -> '}
        case ${'$'}link in
            /*) app_path=${'$'}link ;;
            *) app_path=${'$'}app_dir${'$'}link ;;
        esac
    done
    # -P so a symlinked *bin directory* resolves too: `bin` itself being the link means the
    # loop above never fires, and a logical `cd link/..` lands outside the install tree.
    APP_HOME=${'$'}(CDPATH= cd -P -- "${'$'}{app_dir:-.}/.." && pwd)

    # Java 21 or newer, checked against whichever branch below chose the JVM rather than only
    # the last one. JAVA_HOME is ambient — distro profiles, sdkman/jenv and IDE-launched
    # shells all set it, often to something older — so it is no more a deliberate 21 than PATH
    # is, and AWAKENER_JAVA can name something that is not a JVM at all. Unchecked, every one
    # of those becomes an UnsupportedClassVersionError that names no fix, which is the whole
    # reason this script exists. The cost is one extra `-version` fork per press.
    check_java() {
        # Anchored on the `version "…"` token, not on line 1: JAVA_TOOL_OPTIONS and
        # _JAVA_OPTIONS are as ambient as JAVA_HOME — APM agents, containers, IDE run
        # configurations and CI images all set them — and a JVM that sees one prints
        # `Picked up …` above the version line. Parsing line 1 then reads an empty version,
        # degrades to 0, and rejects a perfectly good JDK 21 with advice it already follows.
        raw=${'$'}("${'$'}1" -version 2>&1 | sed -n 's/.* version "\([^"]*\)".*/\1/p' | head -1)
        major=${'$'}{raw%%.*}
        # 1.8.0_452 and 21.0.4 both have to reduce to a number to compare.
        if [ "${'$'}{major:-}" = 1 ]; then
            major=${'$'}(printf %s "${'$'}raw" | cut -d. -f2)
        fi
        case ${'$'}{major:-x} in
            '' | *[!0-9]*) major=0 ;;
        esac
        if [ "${'$'}major" -lt 21 ]; then
            echo "$name: needs Java 21 or newer, but ${'$'}2 is ${'$'}{raw:-not a JVM}" >&2
            echo "  point AWAKENER_JAVA or JAVA_HOME at a 21+ JDK" >&2
            exit 70
        fi
    }

    if [ -n "${'$'}{AWAKENER_JAVA:-}" ]; then
        JAVACMD=${'$'}AWAKENER_JAVA
        chose="AWAKENER_JAVA=${'$'}AWAKENER_JAVA"
    elif [ -n "${'$'}{JAVA_HOME:-}" ]; then
        JAVACMD=${'$'}JAVA_HOME/bin/java
        chose="JAVA_HOME=${'$'}JAVA_HOME"
    elif [ -x '$buildJava' ]; then
        JAVACMD='$buildJava'
        chose="the JDK this was built with"
    else
        JAVACMD=java
        chose="the java on PATH"
    fi
    check_java "${'$'}JAVACMD" "${'$'}chose"

    exec "${'$'}JAVACMD" -cp "${'$'}APP_HOME/lib/*" $mainClass "${'$'}@"
    """.trimIndent() + "\n"

// Rendered at configuration time so the task body captures strings and nothing else.
val launcherScripts: Map<String, String> = entryPoints.mapValues { (name, main) ->
    launcher(name, main)
}

val launchers by tasks.registering {
    description = "Writes the start scripts for every entry point."
    val target = layout.buildDirectory.dir("launchers")
    val scripts = launcherScripts
    inputs.property("scripts", scripts)
    outputs.dir(target)
    doLast {
        val dir = target.get().asFile
        dir.mkdirs()
        scripts.forEach { (name, text) ->
            File(dir, name).apply {
                writeText(text)
                setExecutable(true)
            }
        }
    }
}

tasks.register<Sync>("installDist") {
    group = "distribution"
    description = "Lays out runnable CLIs under build/install/awakener: put its bin/ on PATH."
    into(layout.buildDirectory.dir("install/awakener"))
    into("lib") {
        from(tasks.named("jvmJar"))
        from(configurations.named("jvmRuntimeClasspath"))
    }
    into("bin") {
        from(launchers)
        filePermissions { unix("rwxr-xr-x") }
    }
}

/** Whether every one of [tools] is an executable on this build's PATH. */
fun onPath(vararg tools: String): Boolean {
    val entries = System.getenv("PATH").orEmpty().split(File.pathSeparator)
    return tools.all { tool -> entries.any { dir -> File(dir, tool).canExecute() } }
}

tasks.withType<Test>().configureEach {
    // So the suite can assert the wiring above actually happened, for whatever the current set
    // of modules is rather than for a set frozen into a test.
    systemProperty("awakener.modules", siblingModules.joinToString(",") { it.removePrefix(":") })

    // This module now has an integration suite of its own, so it inherits both tool gates whole.
    // The invoke path needs sway and foot to stand a dock up, and spanreed to answer whether a
    // Lifeless is animated; `AWAKENER_REQUIRE_*=1` turns a missing tool from a skip into a
    // failure, which is what stops a green run that verified nothing.
    System.getenv("AWAKENER_REQUIRE_SWAY")?.let { environment("AWAKENER_REQUIRE_SWAY", it) }
    System.getenv("AWAKENER_REQUIRE_SPANREED")?.let {
        environment("AWAKENER_REQUIRE_SPANREED", it)
    }

    // Gradle treats neither PATH nor the environment as a test input, so without these the build
    // cache will replay a run that skipped every tool-gated test into a `clean build` that
    // demanded the tools. Same declaration as `:wm` and `:registry`, and for the same measured
    // reason — a REQUIRE=1 clean build coming back in under a second with everything skipped.
    inputs.property("swayTooling", onPath("sway", "foot"))
    inputs.property("requireSway", System.getenv("AWAKENER_REQUIRE_SWAY").orEmpty())
    inputs.property("spanreedTooling", onPath("spanreed"))
    inputs.property("requireSpanreed", System.getenv("AWAKENER_REQUIRE_SPANREED").orEmpty())

    testLogging {
        showStandardStreams = true
        events("passed", "skipped", "failed")
    }
}
